using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using UnityEngine;
namespace Jimothy.Tests {
public class ExpeditionRulesTests {
 static Dictionary<string,ItemDefinition> Items()=>new[]{new ItemDefinition{id="food",category="food",value=2},new ItemDefinition{id="coin",category="valuable",value=7},new ItemDefinition{id="trophy",category="trophy",value=50},new ItemDefinition{id="item_176",category="curio"},new ItemDefinition{id="item_178",category="curio"},new ItemDefinition{id="item_188",category="curio"}}.ToDictionary(i=>i.id);
 static SaveData Fresh()=>new SaveData{loopRevision=1,mapRevision=3,nightGoal=3,x=-14,y=-2.35f,z=59};
 [Test] public void NineOutingsCoverAllGoalEventPairs(){var pairs=new HashSet<string>();for(int n=1;n<=9;n++)pairs.Add(((n-1)%3)+":"+ExpeditionRules.EventForRun(n));Assert.AreEqual(9,pairs.Count);}
 [Test] public void MigrationPreservesLegacyLooseAndBankedProgress(){var d=Fresh();d.loopRevision=0;d.coins=71;d.bag.Add("food");d.pantry.Add("coin");d.trophies.Add("trophy");d.decor.Add("cushion");ExpeditionRules.Migrate(d,new(-14,-2.35f,59));Assert.IsTrue(d.runActive);Assert.AreEqual(71,d.coins);CollectionAssert.AreEqual(new[]{"food"},d.bag);CollectionAssert.Contains(d.bankedDiscoveries,"trophy");CollectionAssert.Contains(d.decor,"cushion");d.selectedGoal=2;ExpeditionRules.Migrate(d,Vector3.zero);Assert.AreEqual(2,d.selectedGoal);}
 [Test] public void EmptyDenMigrationWaitsForDepartureButOutsideResumes(){var den=new Vector3(-14,-2.35f,59);var a=Fresh();a.loopRevision=0;ExpeditionRules.Migrate(a,den);Assert.IsFalse(a.runActive);var b=Fresh();b.loopRevision=0;b.z=44;ExpeditionRules.Migrate(b,den);Assert.IsTrue(b.runActive);}
 [Test] public void RepeatedStartAndSerializedResumeDoNotReroll(){var d=Fresh();Assert.IsTrue(ExpeditionRules.Start(d,123));d.bag.Add("food");d.pendingCoins=7;d.cooldowns.Add(new NodeCooldown{node=4,harvests=1,readyAt=double.MaxValue});string before=JsonUtility.ToJson(d);Assert.IsFalse(ExpeditionRules.Start(d,999));Assert.AreEqual(before,JsonUtility.ToJson(d));var loaded=JsonUtility.FromJson<SaveData>(before);ExpeditionRules.Migrate(loaded,Vector3.zero);Assert.IsFalse(ExpeditionRules.Start(loaded,99));Assert.AreEqual(123,loaded.forageSeed);Assert.AreEqual(7,loaded.pendingCoins);Assert.AreEqual(double.MaxValue,loaded.cooldowns[0].readyAt);}
 [Test] public void EmptyBankDoesNotSettleOrRotate(){var d=Fresh();ExpeditionRules.Start(d,1);Assert.AreEqual(0,ExpeditionRules.Bank(d,Items()));Assert.IsTrue(d.runActive);Assert.AreEqual(0,d.bankedRuns);Assert.IsFalse(ExpeditionRules.Start(d,2));Assert.AreEqual(1,d.runNumber);}
 [Test] public void BankingSettlesPendingValueAndGoalExactlyOnce(){var d=Fresh();ExpeditionRules.Start(d,1);d.selectedGoal=1;d.pendingCoins=14;d.bag.AddRange(new[]{"coin","coin"});Assert.AreEqual(26,ExpeditionRules.Bank(d,Items()));Assert.AreEqual(26,d.coins);Assert.AreEqual(2,d.pantry.Count);Assert.AreEqual(1,d.bankedDiscoveries.Count);Assert.AreEqual(0,d.pendingCoins);Assert.IsFalse(d.runActive);Assert.AreEqual(0,ExpeditionRules.Bank(d,Items()));var restored=JsonUtility.FromJson<SaveData>(JsonUtility.ToJson(d));Assert.AreEqual(0,ExpeditionRules.Bank(restored,Items()));Assert.AreEqual(26,restored.coins);Assert.AreEqual(1,restored.bankedRuns);}
 [Test] public void DeathReleasesLooseTrophyCooldownWithoutTouchingCollection(){var d=Fresh();ExpeditionRules.Start(d,1);d.coins=53;d.bag.Add("trophy");d.pendingCoins=9;d.health=0;d.hunger=0;d.survivalSeconds=245;d.trophies.Add("old-trophy");d.pantry.Add("food");d.decor.Add("cushion");d.cooldowns.Add(new NodeCooldown{node=3,readyAt=double.MaxValue});ExpeditionRules.Lose(d);ExpeditionRules.Lose(d);Assert.IsEmpty(d.bag);Assert.IsEmpty(d.cooldowns);Assert.AreEqual(0,d.pendingCoins);Assert.AreEqual(53,d.coins);Assert.AreEqual(1,d.failedRuns);Assert.AreEqual(1,d.lastLoss);Assert.AreEqual(245,d.bestSeconds);Assert.AreEqual(245,d.survivalSeconds);Assert.AreEqual(100,d.health);Assert.AreEqual(100,d.hunger);CollectionAssert.Contains(d.trophies,"old-trophy");CollectionAssert.Contains(d.pantry,"food");CollectionAssert.Contains(d.decor,"cushion");Assert.IsTrue(ExpeditionRules.Start(d,2));}
 [Test] public void CollectionUnlockRequiresBankingAndDoesNotDuplicatePurchasedDecor(){var d=Fresh();ExpeditionRules.Start(d,1);d.decor.Add("vinyl-wall");d.bag.AddRange(new[]{"item_176","item_178","item_188"});Assert.IsEmpty(d.collectionClaims);ExpeditionRules.Bank(d,Items());CollectionAssert.AreEqual(new[]{"vinyl-wall"},d.collectionClaims);Assert.AreEqual(1,d.decor.Count(x=>x=="vinyl-wall"));ExpeditionRules.Start(d,2);d.bag.Add("item_176");ExpeditionRules.Bank(d,Items());Assert.AreEqual(1,d.collectionClaims.Count);}
 [Test] public void GoalProofIsCarriedItemsAndRotationOccursOnlyNewRun(){var d=Fresh();ExpeditionRules.Start(d,4);d.bag.AddRange(new[]{"food","food","food"});Assert.IsTrue(ExpeditionRules.GoalComplete(d,Items()));d.bag.RemoveAt(0);Assert.IsFalse(ExpeditionRules.GoalComplete(d,Items()));Assert.AreEqual("2 / 3",ExpeditionRules.GoalProgress(d,Items()));ExpeditionRules.Bank(d,Items());int oldEvent=d.nightEvent;ExpeditionRules.Start(d,4);Assert.AreEqual(1,d.selectedGoal);Assert.AreEqual((oldEvent+1)%3,d.nightEvent);}
 [Test] public void ActiveRunOfflineClockFreezesAndInvalidPendingIsRejected(){var d=Fresh();d.savedUtc=100;d.worldSeconds=90;d.runActive=true;d.ApplyOffline(100+86400);Assert.AreEqual(90,d.worldSeconds);Assert.AreEqual(86500,d.savedUtc);Assert.IsTrue(d.Valid());d.pendingCoins=-1;Assert.IsFalse(d.Valid());d.pendingCoins=0;d.selectedGoal=3;Assert.IsFalse(d.Valid());}
 [Test] public void LegacyConsumedCooldownBecomesConsumedRunNode(){var d=Fresh();d.loopRevision=0;d.worldSeconds=30;d.cooldowns.Add(new NodeCooldown{node=1,readyAt=400});d.cooldowns.Add(new NodeCooldown{node=2,readyAt=20});ExpeditionRules.Migrate(d,new(-14,-2.35f,59));Assert.AreEqual(1,d.cooldowns[0].harvests);Assert.AreEqual(0,d.cooldowns[1].harvests);}
 [Test] public void PendingOnlyExtractionPaysAndExistingTrophyDoesNotMintAnotherBonus(){var d=Fresh();ExpeditionRules.Start(d,1);d.pendingCoins=5;Assert.AreEqual(5,ExpeditionRules.Bank(d,Items()));ExpeditionRules.Start(d,1);d.selectedGoal=0;d.trophies.Add("trophy");d.bag.Add("trophy");Assert.AreEqual(0,ExpeditionRules.Bank(d,Items()));Assert.AreEqual(1,d.trophies.Count);Assert.IsFalse(d.runActive);Assert.AreEqual(2,d.bankedRuns);}
 }
}
