using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;
namespace Jimothy {
/// <summary>Authored closing-time district. Coordinates and landing surfaces are shared by visuals and gameplay.</summary>
public static partial class ClosingTimeWorld {
 public struct ScavengeSpot { public string id,itemId; public Vector3 position; public bool rooftop; public ScavengeSpot(string id,string item,Vector3 p,bool roof=false){this.id=id;itemId=item;position=p;rooftop=roof;} }
 public static Vector3 Home=>DenInterior;
 public static readonly List<ScavengeSpot> Spots=new();
 public static readonly List<Vector3> RouteStarts=new();
 public static readonly List<Vector3[]> RoofRoutes=new();
 static readonly Dictionary<string,Material> mats=new();
 static readonly Dictionary<string,Batch> batches=new();
 static readonly System.Collections.Generic.HashSet<string> legacyBatchKeys=new();
 static Transform root; static System.Random random; static int detailCount;
 static Color C(float r,float g,float b)=>new(r,g,b);
 class Batch { public Material material;public List<Vector3> v=new();public List<Vector3> n=new();public List<Vector2> uv=new();public List<int> t=new(); }
 static Material Mat(string key,Color color,float smooth=0,float metal=0,Color? emission=null){if(mats.TryGetValue(key,out var old))return old;var m=new Material(Shader.Find(key=="water"?"Jimothy/WetAsphalt":key=="leaf"||key=="leafLight"?"Jimothy/FoliageVisibility":"Universal Render Pipeline/Lit")){name=key};m.SetColor("_BaseColor",color);m.SetFloat("_Smoothness",smooth);m.SetFloat("_Metallic",metal);m.enableInstancing=true;if(emission.HasValue){m.EnableKeyword("_EMISSION");m.SetColor("_EmissionColor",emission.Value);m.globalIlluminationFlags=MaterialGlobalIlluminationFlags.BakedEmissive;}mats.Add(key,m);return m;}
 static Texture2D SurfaceTexture(string name,Color a,Color b,bool brick=false){int size=512;var tex=new Texture2D(size,size,TextureFormat.RGBA32,true,false){name=name,wrapMode=TextureWrapMode.Repeat,filterMode=FilterMode.Trilinear,anisoLevel=2};var colors=new Color32[size*size];for(int y=0;y<size;y++)for(int x=0;x<size;x++){float noise=Mathf.PerlinNoise(x*.14f,y*.14f)*.5f+Mathf.PerlinNoise(x*.034f,y*.034f)*.5f;var color=Color.Lerp(a,b,noise);if(brick){int row=y/32;int xx=(x+(row%2)*64)%128;float edge=Mathf.Min(xx,127-xx,y%32,31-y%32);if(edge<2)color=Color.Lerp(C(.23f,.21f,.18f),color,edge/2);else color*=.83f+(Mathf.Sin(row*87.3f+(x+(row%2)*64)/128*21.1f)*.5f+.5f)*.28f;}colors[y*size+x]=color;}tex.SetPixels32(colors);tex.Apply(true,true);return tex;}
 static Texture2D brickNormal;
 static Texture2D BrickNormal(){if(brickNormal)return brickNormal;int n=512;var tex=new Texture2D(n,n,TextureFormat.RGBA32,true,true){name="Handmade brick relief",wrapMode=TextureWrapMode.Repeat,filterMode=FilterMode.Trilinear};var pixels=new Color32[n*n];float Height(int x,int y){x=(x+n)%n;y=(y+n)%n;int row=y/32,xx=(x+(row%2)*64)%128;float edge=Mathf.Min(xx,127-xx,y%32,31-y%32);return Mathf.SmoothStep(0,1,edge/4)*.8f+Mathf.PerlinNoise(x*.12f,y*.12f)*.12f;}for(int y=0;y<n;y++)for(int x=0;x<n;x++){var normal=new Vector3((Height(x-1,y)-Height(x+1,y))*1.7f,(Height(x,y-1)-Height(x,y+1))*1.7f,1).normalized;pixels[y*n+x]=new Color(normal.x*.5f+.5f,normal.y*.5f+.5f,normal.z*.5f+.5f,1);}tex.SetPixels32(pixels);tex.Apply(true,true);brickNormal=tex;return tex;}
 static void Pbr(string material,string texture,float tile,Color tint){var m=mats[material];var color=Resources.Load<Texture2D>("Surfaces/"+texture+"_BaseColor");if(!color)return;m.SetTexture("_BaseMap",color);m.SetColor("_BaseColor",tint);m.SetTextureScale("_BaseMap",Vector2.one*tile);var normal=Resources.Load<Texture2D>("Surfaces/"+texture+"_Normal");if(normal){m.SetTexture("_BumpMap",normal);m.SetFloat("_BumpScale",.65f);m.EnableKeyword("_NORMALMAP");}var mask=Resources.Load<Texture2D>("Surfaces/"+texture+"_Mask");if(mask){m.SetTexture("_MetallicGlossMap",mask);m.SetFloat("_Smoothness",.85f);m.EnableKeyword("_METALLICSPECGLOSSMAP");}}
 static void Materials(){if(mats.Count>0)return;
  var brick=SurfaceTexture("Weathered running-bond brick",C(.25f,.11f,.06f),C(.59f,.31f,.17f),true);
  foreach(var key in new[]{"brickRust","brickUmber","brickPaint","brickOchre"}){var m=Mat(key,key=="brickPaint"?C(.58f,.63f,.57f):key=="brickUmber"?C(.53f,.41f,.35f):key=="brickOchre"?C(.97f,.81f,.55f):Color.white,.17f);m.SetTexture("_BaseMap",brick);m.SetTexture("_BumpMap",BrickNormal());m.SetFloat("_BumpScale",.7f);m.EnableKeyword("_NORMALMAP");}
  Mat("stone",C(.52f,.48f,.36f),.23f);Mat("iron",C(.035f,.052f,.048f),.48f,.55f);Mat("copper",C(.095f,.24f,.21f),.4f,.5f);Mat("cream",C(.84f,.78f,.57f),.15f);Mat("roof",C(.085f,.115f,.13f),.34f);Mat("wood",C(.27f,.15f,.07f),.19f);Mat("cedar",C(.42f,.26f,.13f),.22f);Mat("leaf",C(.17f,.32f,.12f),.32f);Mat("leafLight",C(.30f,.43f,.18f),.32f);Mat("moss",C(.10f,.18f,.09f),.18f);Mat("gold",C(.68f,.44f,.13f),.62f,.65f);Mat("awning",C(.025f,.16f,.13f),.2f);Mat("awningRed",C(.38f,.09f,.05f),.2f);
  var road=Mat("asphalt",C(.27f,.29f,.31f),.40f,.07f);road.SetTexture("_BaseMap",SurfaceTexture("Wet road aggregate",C(.17f,.20f,.21f),C(.30f,.32f,.31f)));
  var pave=Mat("paving",C(.55f,.57f,.52f),.46f);pave.SetTexture("_BaseMap",SurfaceTexture("Worn granite",C(.38f,.39f,.37f),C(.68f,.67f,.60f)));
  Mat("glass",C(.085f,.17f,.18f),.88f,.35f);Mat("window",C(.56f,.31f,.12f),.45f,.05f,C(.52f,.31f,.14f));Mat("windowDim",C(.22f,.16f,.08f),.35f,0,C(.12f,.085f,.055f));Mat("bulb",C(1,.75f,.33f),.25f,0,C(5.0f,3.4f,1.65f));Mat("neon",C(.4f,.85f,.7f),.2f,0,C(.3f,2.4f,1.65f));Mat("amber",C(1,.48f,.13f),.2f,0,C(.8f,.40f,.12f));Mat("water",C(.025f,.04f,.045f),.82f,.04f);Mat("lanternGlass",C(1,.78f,.46f),.35f,0,C(2.8f,1.9f,.85f));Mat("paper",C(.57f,.51f,.37f),.1f);
  ArtMaterials();
  Pbr("brickRust","Brick",1,Color.white);Pbr("brickUmber","Brick",1,C(.61f,.60f,.56f));Pbr("brickOchre","Brick",1,C(.92f,.85f,.65f));Pbr("brickPaint","Brick",1,C(.82f,.86f,.79f));Pbr("asphalt","Asphalt",.3333f,C(.64f,.70f,.73f));mats["water"].SetTexture("_BaseMap",mats["asphalt"].GetTexture("_BaseMap"));mats["water"].SetColor("_BaseColor",mats["asphalt"].GetColor("_BaseColor"));Pbr("roof","Asphalt",.65f,C(.36f,.40f,.43f));mats["roof"].SetFloat("_Smoothness",.38f);Pbr("wood","Wood",2,C(.63f,.47f,.31f));Pbr("cedar","Wood",2,C(.83f,.69f,.46f));
 }
 static Batch GetBatch(string material,Vector3 p){
  // Compare partitions on identical authored geometry; this is a mesh-count measurement, not an FPS estimate.
  legacyBatchKeys.Add(material+"_"+Mathf.FloorToInt((p.z+48)/16));
  bool distant=p.z< -49||p.z>56;
  bool translucentOrFoliage=material=="water"||material=="leaf"||material=="leafLight";
  bool smallUnshadowed=material=="bulb"||material=="amber"||material=="neon"||material=="paper";
  float cell=material=="streetBrick"?8:distant||translucentOrFoliage?16:smallUnshadowed?64:16;
  string key=material+"_"+(distant?"distant_":"near_")+Mathf.FloorToInt((p.z+48)/cell);
  if(!batches.TryGetValue(key,out var batch)){batch=new Batch{material=mats[material]};batches.Add(key,batch);}return batch;
 }

 static void Box(string name,Vector3 p,Vector3 size,string material,bool solid=false,Quaternion? rotation=null){var q=rotation??Quaternion.identity;var b=GetBatch(material,p);var h=size*.5f;Vector3[] normals={Vector3.right,Vector3.left,Vector3.up,Vector3.down,Vector3.forward,Vector3.back};Vector3[] u={Vector3.back,Vector3.forward,Vector3.right,Vector3.right,Vector3.right,Vector3.left};Vector3[] v={Vector3.up,Vector3.up,Vector3.back,Vector3.forward,Vector3.up,Vector3.up};for(int f=0;f<6;f++){int k=b.v.Count;var nn=normals[f];var uu=u[f];var vv=v[f];var center=Vector3.Scale(nn,h);float su=Vector3.Scale(uu,h).magnitude,sv=Vector3.Scale(vv,h).magnitude;foreach(var xy in new[]{new Vector2(-1,-1),new Vector2(1,-1),new Vector2(1,1),new Vector2(-1,1)}){b.v.Add(p+q*(center+uu*su*xy.x+vv*sv*xy.y));b.n.Add(q*nn);b.uv.Add(new Vector2((xy.x+1)*su,(xy.y+1)*sv));}b.t.AddRange(new[]{k,k+1,k+2,k,k+2,k+3});}
  if(solid){var go=new GameObject(name);go.transform.SetParent(root,false);go.transform.localPosition=p;go.transform.localRotation=q;go.AddComponent<BoxCollider>().size=size;}detailCount++;
 }
 static void Cylinder(string name,Vector3 a,Vector3 b,float radius,string material,int sides=8){var q=Quaternion.FromToRotation(Vector3.up,(b-a).normalized);var batch=GetBatch(material,a);float len=(b-a).magnitude;for(int i=0;i<sides;i++){float t=i*Mathf.PI*2/sides,t2=(i+1)*Mathf.PI*2/sides;Vector3 n1=q*new Vector3(Mathf.Cos(t),0,Mathf.Sin(t)),n2=q*new Vector3(Mathf.Cos(t2),0,Mathf.Sin(t2));int k=batch.v.Count;batch.v.AddRange(new[]{a+n1*radius,b+n1*radius,b+n2*radius,a+n2*radius});batch.n.AddRange(new[]{n1,n1,n2,n2});batch.uv.AddRange(new[]{new Vector2(0,0),new Vector2(0,len),new Vector2(1,len),new Vector2(1,0)});batch.t.AddRange(new[]{k,k+1,k+2,k,k+2,k+3});}detailCount++;}
 static Material fontMaterial;
 static void Text(string text,Vector3 p,float size,string material,Quaternion rotation){var go=new GameObject("Sign: "+text);go.transform.SetParent(root,false);go.transform.localPosition=p;go.transform.rotation=rotation;var label=go.AddComponent<TextMesh>();label.text=text;label.fontSize=72;label.characterSize=size;label.anchor=TextAnchor.MiddleCenter;label.alignment=TextAlignment.Center;label.fontStyle=FontStyle.Bold;label.color=mats[material].GetColor("_BaseColor");var renderer=go.GetComponent<MeshRenderer>();renderer.shadowCastingMode=ShadowCastingMode.Off;if(!fontMaterial){fontMaterial=new Material(Shader.Find("Jimothy/WorldLettering"));fontMaterial.mainTexture=label.font.material.mainTexture;}renderer.sharedMaterial=fontMaterial;}
 static void PoleLamp(Vector3 p){Cylinder("Fluted lamp",p,p+Vector3.up*4.2f,.065f,"iron",10);Box("Lantern foot",p+Vector3.up*.15f,new(.28f,.30f,.28f),"iron");Box("Lantern glass",p+Vector3.up*4.1f,new(.35f,.48f,.35f),"lanternGlass");Box("Lantern cap",p+Vector3.up*4.4f,new(.49f,.12f,.49f),"iron");for(int sx=-1;sx<=1;sx+=2)for(int sz=-1;sz<=1;sz+=2)Cylinder("Lantern frame",p+new Vector3(sx*.19f,3.84f,sz*.19f),p+new Vector3(sx*.19f,4.35f,sz*.19f),.022f,"iron");Light(p+Vector3.up*3.9f,C(1,.76f,.49f),10.5f,10.0f);}
 static void Light(Vector3 p,Color color,float range,float power){var go=new GameObject("Local warm light");go.transform.SetParent(root,false);go.transform.position=p;var l=go.AddComponent<Light>();l.type=LightType.Point;l.color=color;l.range=range;l.intensity=power;l.shadows=LightShadows.None;go.AddComponent<ClosingLight>();}
 static void Crate(Vector3 p,Vector3 size){Box("Climbable crate",p,size,"wood",true);for(int i=-1;i<=1;i++)Box("Crate plank",p+new Vector3(0,i*size.y*.28f,-size.z*.51f),new(size.x,.055f,.04f),"cedar");foreach(int side in new[]{-1,1})Box("Crate reinforcing strip",p+new Vector3(side*size.x*.38f,0,-size.z*.53f),new(.08f,size.y,.035f),"cedar");}
 static void AC(Vector3 p,Vector3 size){Box("AC landing",p,size,"copper",true);Box("AC cap",p+Vector3.up*(size.y*.5f+.035f),new(size.x+.12f,.07f,size.z+.12f),"iron");for(int j=0;j<10;j++)Box("Vent grille",p+new Vector3(-size.x*.42f+j*size.x*.084f,0,-size.z*.505f),new(.045f,size.y*.66f,.025f),"iron");}
 static void Planter(Vector3 p){Box("Cedar planter",p+Vector3.up*.3f,new(1,.6f,.7f),"wood",true);Box("Damp earth",p+Vector3.up*.61f,new(.88f,.02f,.58f),"moss");foreach(int side in new[]{-1,1})Box("Planter corner strap",p+new Vector3(side*.43f,.3f,-.36f),new(.055f,.58f,.025f),"iron");foreach(int edge in new[]{-1,1}){Box("Planter top side rim",p+new Vector3(edge*.48f,.62f,0),new(.06f,.08f,.74f),"cedar");Box("Planter top end rim",p+new Vector3(0,.62f,edge*.34f),new(.94f,.08f,.06f),"cedar");}Fern(p+new Vector3(-.15f,.625f,0),.50f);Fern(p+new Vector3(.20f,.625f,.025f),.42f);}
 static void Ellipsoid(Vector3 p,Vector3 scale,string material,int segments=9,int rings=5){var batch=GetBatch(material,p);for(int y=0;y<rings;y++)for(int x=0;x<segments;x++){int k=batch.v.Count;foreach(var uv in new[]{new Vector2(x,y),new Vector2(x+1,y),new Vector2(x+1,y+1),new Vector2(x,y+1)}){float a=uv.x/segments*Mathf.PI*2,b=uv.y/rings*Mathf.PI;var n=new Vector3(Mathf.Sin(b)*Mathf.Cos(a),Mathf.Cos(b),Mathf.Sin(b)*Mathf.Sin(a));batch.v.Add(p+Vector3.Scale(n,scale));batch.n.Add(new Vector3(n.x/scale.x,n.y/scale.y,n.z/scale.z).normalized);batch.uv.Add(uv/new Vector2(segments,rings));}batch.t.AddRange(new[]{k,k+1,k+2,k,k+2,k+3});}detailCount++;}
 static void Puddle(Vector3 p,float rx,float rz){var batch=GetBatch("water",p);int k=batch.v.Count;batch.v.Add(p);batch.n.Add(Vector3.up);batch.uv.Add(Vector2.zero);for(int i=0;i<=20;i++){float a=i/20f*Mathf.PI*2;float wav=1+Mathf.Sin(a*3+.4f)*.17f+Mathf.Sin(a*7)*.09f;batch.v.Add(p+new Vector3(Mathf.Cos(a)*rx*wav,0,Mathf.Sin(a)*rz*wav));batch.n.Add(Vector3.up);batch.uv.Add(new Vector2(Mathf.Cos(a),Mathf.Sin(a)));}for(int i=0;i<20;i++)batch.t.AddRange(new[]{k,k+i+2,k+i+1});}
 static void Tree(Vector3 p){TreeOrganic(p);}
 static void Window(int side,float front,float z,float y,bool bright,int variant){float x=front-side*.14f;Box("Window recess",new(x,y,z),new(.14f,1.95f,1.28f),"iron");Box("Lit window",new(x-side*.08f,y,z),new(.025f,1.66f,1.07f),bright?"window":"windowDim");foreach(float zz in new[]{z-.69f,z+.69f})Box("Window pilaster",new(x-side*.09f,y,zz),new(.15f,2.12f,.13f),"stone");Box("Window lintel",new(x-side*.10f,y+1.05f,z),new(.20f,.18f,1.51f),"stone");Box("Projecting sill",new(x-side*.20f,y-.99f,z),new(.40f,.14f,1.55f),"stone");Box("Mullion",new(x-side*.13f,y,z),new(.04f,1.66f,.045f),"iron");Box("Transom",new(x-side*.13f,y+.3f,z),new(.04f,.045f,1.10f),"iron");if(variant%3==0)Box("Drawn curtain",new(x-side*.105f,y,z+.38f),new(.025f,1.62f,.22f),"cream");}
 static void Building(int side,int row){float z=-30+row*16;float x=side*14.6f;float h=new[]{7.2f,8.1f,9f,7.2f,8.1f}[row];float front=side*9.4f;string brick=new[]{"brickRust","brickUmber","brickPaint","brickOchre","brickRust"}[(row+(side>0?1:0))%5];Box("Building solid",new(x,h*.5f,z),new(10.4f,h,12.2f),brick,true);Box("Flat roof",new(x,h+.09f,z),new(10.65f,.18f,12.45f),"roof",true);
  foreach(float yy in new[]{.35f,3.3f,h-.35f}){Box("Stone cornice",new(x,yy,z),new(10.85f,.16f,12.55f),"stone");Box("Cornice shadow",new(x,yy-.14f,z),new(10.67f,.07f,12.38f),"iron");}
  RoofCoping(side,x,z,h);
  for(int i=0;i<17;i++)Box("Cornice dentil",new(front-side*.27f,h-.15f,z-5.6f+i*.7f),new(.38f,.30f,.22f),"stone");
  // Landing edge is deliberately open beside the alley route; parapets stop short of it.
  Box("Back parapet",new(x+side*5.1f,h+.44f,z),new(.20f,.55f,11.8f),brick,true);Box("Front parapet",new(front,h+.44f,z),new(.20f,.55f,11.8f),brick,true);Box("South parapet",new(x,h+.44f,z-6.05f),new(10.4f,.55f,.20f),brick,true);
  for(int j=0;j<5;j++){float zz=z-4.7f+j*2.35f;Window(side,front,zz,4.9f,(row+j)%4!=0,j);if(h>8.5f)Window(side,front,zz,7.15f,(j+row)%3==0,j);}
  string[] names=side<0?new[]{"THE NET LOFT","CEDAR & SALT","BALLARD BAKERY","THE LAST CAST","SALMON & SONS"}:new[]{"THE COPPER GULL","OLD AVENUE","JUNIPER ROOM","DOCKSIDE COFFEE","NORTHWEST RECORDS"};
  for(int j=0;j<4;j++)DeepShop(side,row,j,front,z-4.55f+j*3f);
  BuildingCharacter(side,row,front,z,h);
  BrandShop(side,row,front,z,h);
  FacadeGarden(side,row,front,z);
  Cylinder("Downpipe",new(front-side*.32f,.15f,z+5.85f),new(front-side*.32f,h-.4f,z+5.85f),.045f,"copper");
  AC(new(x-side*2.4f,h+.55f,z-2),new(1.8f,.85f,1.6f));Box("Chimney",new(x+side*2,h+.75f,z+1.4f),new(.85f,1.3f,.85f),brick);Box("Chimney cap",new(x+side*2,h+1.42f,z+1.4f),new(1.12f,.14f,1.12f),"stone");
  for(int k=0;k<4;k++)Box("Roof timber deck",new(x-side*2,h+.2f,z+2.2f+k*.45f),new(3.0f,.09f,.40f),"cedar");Planter(new(x+side*1.5f,h+.2f,z+3.5f));
  // Concrete, short, climbable sequence: crate -> fridge -> vent -> service landings -> roof.
  float alleyZ=z+6.95f;var route=new List<Vector3>();float rise=.9f;int steps=Mathf.RoundToInt(h/rise);for(int k=0;k<steps;k++){float px=side*(8.1f+k*1.03f);float top=.2f+(k+1)*rise;Vector3 p=new(px,top*.5f,alleyZ);Vector3 size=new(1.5f,top,1.5f);if(k<2)Crate(p,size);else if(k==2)AC(p,size);else {Box("Service landing",new(px,top-.13f,alleyZ),new(1.5f,.26f,1.5f),"iron",true);foreach(float dz in new[]{-.56f,.56f})Cylinder("Landing support",new(px-side*.5f,.18f,alleyZ+dz),new(px-side*.5f,top-.24f,alleyZ+dz),.055f,"iron");}
   Box("Amber landing lip",new(px,top+.017f,alleyZ+.65f),new(1.35f,.028f,.065f),"amber");route.Add(new(px,top+.04f,alleyZ));if(k%3==0){Box("Route paw",new(px-side*.20f-.14f,top+.025f,alleyZ),new(.17f,.022f,.21f),"cream");Box("Route paw",new(px-side*.20f+.14f,top+.025f,alleyZ-.18f),new(.17f,.022f,.21f),"cream");}}
  float landingX=side*(8.1f+(steps-1)*1.03f);Box("Roof access bridge",new(landingX,h+.10f,z+6.2f),new(1.55f,.20f,1.8f),"iron",true);route.Add(new(landingX,h+.24f,z+5.7f));RoofRoutes.Add(route.ToArray());RouteStarts.Add(new(side*7.0f,.24f,alleyZ));Box("Rooftop wayfinding plate",new(side*6.35f,.78f,alleyZ+.85f),new(.85f,.58f,.07f),"awning");Cylinder("Route sign post",new(side*6.35f,.2f,alleyZ+.85f),new(side*6.35f,.54f,alleyZ+.85f),.045f,"iron");Text("ROOF\n↑",new(side*6.35f,.80f,alleyZ+.90f),.026f,"cream",Quaternion.Euler(0,180,0));Light(new(side*8.0f,2.4f,alleyZ+.3f),C(1,.61f,.22f),4,2.5f);
  if(row%2==0)Spots.Add(new("roof_"+side+"_"+row,side<0?(row==0?"trophy_00":row==2?"trophy_01":"trophy_02"):(row==0?"trophy_04":row==2?"trophy_05":"trophy_06"),new(x-side*2,h+.35f,z+2.6f),true));
  // Back-door finds live beside props, never in traffic lanes.
  Vector3 bin=new(side*8.3f,.7f,z-5.7f);Box("Restaurant dumpster",bin,new(1.30f,1.05f,1.05f),"copper",true);Box("Bin lid",bin+Vector3.up*.58f,new(1.40f,.10f,1.16f),"iron");Box("Recycling sticker",bin+new Vector3(0,.12f,.54f),new(.48f,.32f,.012f),"cream");Spots.Add(new("kitchen_"+side+"_"+row,(side<0?new[]{"item_136","item_048","item_016","item_054","item_000"}:new[]{"item_052","item_070","item_090","item_030","item_188"})[row],new(side*7.40f,.40f,z-5.55f)));
  if(row%2==1){Crate(new(side*8.0f,.43f,z+4.8f),new(1.1f,.65f,.8f));Spots.Add(new("patio_"+side+"_"+row,side<0?(row==1?"item_036":"item_058"):(row==1?"item_096":"item_220"),new(side*8.0f,.92f,z+4.8f)));}
  Light(new(front-side*1.8f,2.65f,z),C(1,.72f,.45f),6.5f,4.5f);
 }
 public static GameObject Build(Transform parent){Materials();Spots.Clear();RouteStarts.Clear();RoofRoutes.Clear();batches.Clear();legacyBatchKeys.Clear();random=new System.Random(46);detailCount=0;var go=new GameObject("Ballard Avenue — closing time");go.transform.SetParent(parent,false);root=go.transform;
  DenGround();foreach(int side in new[]{-1,1}){Box("Granite sidewalk",new(side*7.5f,.10f,9),new(4,.2f,94),"paving",true);for(int z=-38;z<54;z+=2){Box("Granite curb",new(side*5.55f,.12f,z),new(.20f,.26f,1.96f),"stone");Box("Paving seam",new(side*7.4f,.206f,z),new(3.65f,.009f,.016f),"iron");}for(int row=0;row<5;row++)Building(side,row);for(int row=0;row<5;row++){float z=-31+row*16;PoleLamp(new(side*5.95f,.22f,z));Tree(new(side*6.35f,.22f,z+7));Planter(new(side*8.0f,.22f,z+2.8f));}}
  BrickAvenue();
  // Heritage brick surface with wet patches and exposed streetcar seams.
  // Dampness is shaded directly on the brick: no floating asphalt-colored puddle overlays.
  foreach(float x in new[]{-1.0f,1.0f})Box("Old streetcar seam",new(x,.012f,2),new(.035f,.012f,91),"iron");
  for(int i=0;i<13;i++)Box("Crosswalk paint",new(-4.6f+i*.76f,.009f,40),new(.44f,.01f,2),"cream");
  // Patio chairs, tables and closing-time sidewalk clutter.
  foreach(int side in new[]{-1,1})foreach(float z in new[]{-24f,7f,25f}){var p=new Vector3(side*7.55f,.22f,z);Box("Cafe table",p+Vector3.up*.74f,new(.86f,.08f,.74f),"cedar");Cylinder("Table pedestal",p,p+Vector3.up*.7f,.06f,"iron");for(int j=-1;j<=1;j+=2){var chair=p+Vector3.forward*j*.8f;Box("Chair seat",chair+Vector3.up*.42f,new(.43f,.06f,.43f),"wood");Box("Chair back",chair+new Vector3(0,.7f,j*.2f),new(.43f,.5f,.05f),"wood");foreach(int k in new[]{-1,1})foreach(int leg in new[]{-1,1})Cylinder("Chair legs",chair+new Vector3(k*.17f,0,leg*.17f),chair+new Vector3(k*.17f,.43f,leg*.17f),.025f,"iron");}Box("Folded menu",p+Vector3.up*.83f,new(.21f,.015f,.3f),"paper");}
  // Overhead festoons define the street ceiling and pull the eye toward the next block.
  foreach(float z in new[]{-18f,14f,37f})for(int i=0;i<18;i++){float x=-9+i*1.05f,y=6.3f-Mathf.Sin(i/17f*Mathf.PI)*.85f;Cylinder("Festoon wire",new(x,y,z),new(x+1.05f,6.3f-Mathf.Sin((i+1)/17f*Mathf.PI)*.85f,z),.012f,"iron",5);Ellipsoid(new(x,y-.10f,z),new(.047f,.063f,.047f),"bulb",10,6);}
  foreach(float z in new[]{-18f,14f,37f})foreach(float x in new[]{-5.5f,0f,5.5f})Light(new(x,5.2f,z),C(1,.78f,.52f),8.5f,8.0f);
  Den();BellGarden();ParkEdges();LivingGardens();RoofPersonalization();RoundTripWayfinding();Backdrop();Bake();go.AddComponent<ClosingWorldCleanup>().ownedMeshes=createdMeshes.ToArray();createdMeshes.Clear();Debug.Log("CLOSING_TIME_WORLD details="+detailCount+" legacy16mBatches="+legacyBatchKeys.Count+" batches="+batches.Count+" spots="+Spots.Count+" roofRoutes="+RoofRoutes.Count);batches.Clear();legacyBatchKeys.Clear();return go;
 }
 static readonly List<Mesh> createdMeshes=new();
 static void Bake(){foreach(var pair in batches){var b=pair.Value;var m=new Mesh{name="Ballard "+pair.Key,indexFormat=IndexFormat.UInt32};m.SetVertices(b.v);m.SetNormals(b.n);m.SetUVs(0,b.uv);m.SetTriangles(b.t,0);m.RecalculateBounds();m.RecalculateTangents();m.UploadMeshData(Application.isPlaying);createdMeshes.Add(m);var go=new GameObject("Architecture "+pair.Key);go.transform.SetParent(root,false);go.AddComponent<MeshFilter>().sharedMesh=m;var r=go.AddComponent<MeshRenderer>();r.sharedMaterial=b.material;r.shadowCastingMode=pair.Key.StartsWith("window")||pair.Key.StartsWith("glass")||pair.Key.StartsWith("bulb")||pair.Key.StartsWith("lanternGlass")||pair.Key.StartsWith("amber")||pair.Key.StartsWith("neon")||pair.Key.StartsWith("water")||pair.Key.StartsWith("paper")?ShadowCastingMode.Off:ShadowCastingMode.On;r.receiveShadows=true;}}
 static void Den(){DenRoom();}
 static void Bell(){foreach(float x in new[]{-1f,1f})Cylinder("Marvins bell frame",new(x,0,-43),new(x,6.7f,-43),.12f,"iron");Cylinder("Bell lintel",new(-1.3f,6.5f,-43),new(1.3f,6.5f,-43),.12f,"iron");for(int i=0;i<5;i++){float y=5.6f+i*.18f;Box("Historic bell",new(0,y,-43),new(1.25f-i*.17f,.20f,.85f-i*.09f),"gold");}Text("MARVIN'S GARDEN",new(0,1.2f,-42.5f),.036f,"cream",Quaternion.Euler(0,180,0));PoleLamp(new(-2.5f,0,-42));}
 static void Backdrop(){
  DistantNeighborhood();
  RainierScenery();
 }
 public static void ConfigureAtmosphere(Camera cam,Transform parent){cam.backgroundColor=C(.018f,.036f,.07f);cam.clearFlags=CameraClearFlags.Skybox;cam.farClipPlane=330;RenderSettings.ambientMode=AmbientMode.Trilight;RenderSettings.ambientSkyColor=C(.14f,.19f,.27f);RenderSettings.ambientEquatorColor=C(.080f,.105f,.14f);RenderSettings.ambientGroundColor=C(.03f,.04f,.055f);RenderSettings.fog=true;RenderSettings.fogColor=C(.035f,.075f,.12f);RenderSettings.fogMode=FogMode.ExponentialSquared;RenderSettings.fogDensity=.0055f;
  var moon=new GameObject("Moonlight");moon.transform.SetParent(parent,false);moon.transform.rotation=Quaternion.Euler(58,-32,0);var light=moon.AddComponent<Light>();light.type=LightType.Directional;light.color=C(.73f,.83f,1);light.intensity=1.15f;light.shadows=LightShadows.Soft;light.shadowStrength=.82f;light.shadowBias=.035f;light.shadowNormalBias=.20f;var moonData=moon.AddComponent<UnityEngine.Rendering.Universal.UniversalAdditionalLightData>();moonData.usePipelineSettings=false;moonData.softShadowQuality=UnityEngine.Rendering.Universal.SoftShadowQuality.Low;RenderSettings.sun=light;
  var shader=Shader.Find("Jimothy/ClosingTimeSky");if(shader){var sky=new Material(shader);sky.SetVector("_MoonDirection",-light.transform.forward);RenderSettings.skybox=sky;}else{var sky=new Material(Shader.Find("Skybox/Procedural"));sky.SetColor("_SkyTint",C(.06f,.12f,.25f));sky.SetFloat("_Exposure",.2f);RenderSettings.skybox=sky;}
  var volume=parent.gameObject.AddComponent<ClosingAtmosphere>();volume.Initialize(cam,RenderSettings.skybox);
 }
}
public class ClosingLight:MonoBehaviour {
 Light lamp;float power;void Awake(){lamp=GetComponent<Light>();power=lamp.intensity;}
 void Update(){var g=GameSession.Instance;if(!g||!g.Player)return;float distance=Vector3.Distance(g.Player.transform.position,transform.position);float fade=1-Mathf.SmoothStep(0,1,Mathf.InverseLerp(20,30,distance));lamp.enabled=fade>.001f;lamp.intensity=power*fade;}
}
public class ClosingWorldCleanup:MonoBehaviour {public Mesh[] ownedMeshes;void OnDestroy(){if(ownedMeshes!=null)foreach(var m in ownedMeshes)if(m)Destroy(m);}}
public class ClosingAtmosphere:MonoBehaviour {Material ownedSky;VolumeProfile ownedProfile;void OnDestroy(){if(ownedSky){if(RenderSettings.skybox==ownedSky)RenderSettings.skybox=null;Destroy(ownedSky);}if(ownedProfile){foreach(var component in ownedProfile.components)if(component)Destroy(component);Destroy(ownedProfile);}}public void Initialize(Camera camera,Material sky){ownedSky=sky;var data=camera.GetComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>();if(!data)data=camera.gameObject.AddComponent<UnityEngine.Rendering.Universal.UniversalAdditionalCameraData>();data.renderPostProcessing=true;var v=gameObject.AddComponent<Volume>();v.isGlobal=true;v.priority=2;ownedProfile=ScriptableObject.CreateInstance<VolumeProfile>();v.sharedProfile=ownedProfile;var bloom=ownedProfile.Add<UnityEngine.Rendering.Universal.Bloom>();bloom.intensity.Override(.34f);bloom.threshold.Override(1.35f);bloom.scatter.Override(.5f);var tone=ownedProfile.Add<UnityEngine.Rendering.Universal.Tonemapping>();tone.mode.Override(UnityEngine.Rendering.Universal.TonemappingMode.ACES);var color=ownedProfile.Add<UnityEngine.Rendering.Universal.ColorAdjustments>();color.postExposure.Override(.25f);color.contrast.Override(10);color.saturation.Override(-3);}}
}
