using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
namespace Jimothy.Editor {
[InitializeOnLoad] public static class DenExperienceAudit {
 const string Pending="Jimothy.DenExperienceAudit";static GameSession game;static int stage,frame;static double deadline;static string saved;static List<string> displayed;static int cameraSamples;static readonly Dictionary<string,byte[]> originals=new();
 [Serializable] class Report{public bool passed;public List<string> assertions=new();public string error,note="Current NewGame opens the Den night board; its Head out button begins the outing. Actual CharacterController movement exits/reenters/exits the den without teleport or jump after initial NewGame. Inventory fixtures exercise display capacity; JSON roundtrip feeds actual session Begin reconstruction. Native saves remain suppressed and byte-compared. This is not a human playtest or physical-device test.";}
 static Report report;
 static DenExperienceAudit(){EditorApplication.playModeStateChanged+=OnMode;if(SessionState.GetBool(Pending,false))EditorApplication.update+=Tick;}
 public static void Run(){EditorSceneManager.OpenScene("Assets/Jimothy/Scenes/Ballard.unity");SessionState.SetBool(Pending,true);EditorApplication.isPlaying=true;}
 static void OnMode(PlayModeStateChange mode){if(mode==PlayModeStateChange.EnteredPlayMode&&SessionState.GetBool(Pending,false)){stage=0;deadline=EditorApplication.timeSinceStartup+150;EditorApplication.update-=Tick;EditorApplication.update+=Tick;}}
 static void Check(bool result,string description){if(!result)throw new Exception(description);report.assertions.Add(description);}
 static void Next(int value){stage=value;frame=Time.frameCount;}
 static void Walk(params Vector3[] targets){var simulation=Physics.simulationMode;Physics.simulationMode=SimulationMode.Script;game.Player.Running=false;try{foreach(var target in targets){bool reached=false;for(int f=0;f<1600;f++){Vector3 delta=target-game.Player.transform.position;delta.y=0;Vector3 input=delta.magnitude>.06f?delta.normalized*Mathf.Clamp01(delta.magnitude/.25f):Vector3.zero;Physics.SyncTransforms();game.Player.SimulateMovement(input,false,1f/60);Physics.Simulate(1f/60);if(input.sqrMagnitude>.01f&&game.Player.visual)game.Player.visual.rotation=Quaternion.LookRotation(input);game.Player.UpdateFollowCamera(1f/60);var camera=Camera.main;if(camera&&game.Player.transform.position.z>48){cameraSamples++;if(Physics.CheckSphere(camera.transform.position,.07f,1<<0,QueryTriggerInteraction.Ignore))throw new Exception("Follow camera intersects den/ramp at "+camera.transform.position);}
 if(delta.magnitude<.15f&&Mathf.Abs(game.Player.transform.position.y-target.y)<.25f&&game.Player.Grounded){reached=true;break;}}Check(reached,"Walk supported to "+target);}}finally{Physics.simulationMode=simulation;game.Player.Running=true;}}
 static void VerifyDisplays(){var models=UnityEngine.Object.FindObjectsByType<DenDisplayedFind>(FindObjectsSortMode.None);Check(models.Length==displayed.Count,"One physical model per selected unique ID");Check(models.Select(x=>x.itemId).OrderBy(x=>x).SequenceEqual(displayed.OrderBy(x=>x)),"Physical display IDs match curated selection");foreach(var model in models){var mesh=model.GetComponent<MeshFilter>();Check(mesh&&mesh.sharedMesh&&mesh.sharedMesh.vertexCount>12,"Authored mesh present: "+model.itemId);var renderer=model.GetComponent<Renderer>();float gap=ClosingTimeWorld.DenDisplaySlots.Min(slot=>Mathf.Abs(renderer.bounds.min.y-slot.y));Check(gap<.03f,"Display rests at shelf height: "+model.itemId);var floorProbe=new Vector3(renderer.bounds.center.x,renderer.bounds.min.y+.04f,renderer.bounds.center.z);Check(Physics.Raycast(floorProbe,Vector3.down,.12f,1<<0,QueryTriggerInteraction.Ignore),"Shelf physically supports display: "+model.itemId);}}
 static void Tick(){if(!SessionState.GetBool(Pending,false)||!EditorApplication.isPlaying)return;try{
  if(EditorApplication.timeSinceStartup>deadline)throw new Exception("Den audit timed out");
  if(stage==0){game=UnityEngine.Object.FindFirstObjectByType<GameSession>();if(!game)return;report=new Report();originals.Clear();foreach(var suffix in new[]{"",".bak",".tmp"}){string p=SaveStore.PathName+suffix;originals[p]=File.Exists(p)?File.ReadAllBytes(p):null;}game.SuppressSaving=true;game.NewGame();Next(1);return;}
  if(Time.frameCount-frame<20)return;
  if(stage==1){Check(game.AtHome&&(game.Player.transform.position-ClosingTimeWorld.DenInterior).magnitude<.4f,"Fresh adventure starts safely inside Den");
   Check(!game.Data.runActive&&game.Data.runNumber==0&&game.Data.bag.Count==0,"Fresh outing is inactive with empty pockets");
   Check(game.DenOpen&&game.Paused&&!game.Player.Running,"NewGame opens paused night board before departure");
   game.UI.ShowWardrobe(1);Check(game.DenOpen&&game.Paused,"Wardrobe safely pauses at Den");Check(game.Wear("bandana")&&game.ChangeCoat(1),"Starter outfit and coat equip");Check(!game.Wear("crown"),"Unbanked outfit cannot equip");Check(!game.Player.visual.GetComponentsInChildren<Collider>().Any(c=>c.enabled),"Cosmetics add no active colliders");game.UI.ShowNightBoard();
   var depart=game.UI.GetComponentsInChildren<UnityEngine.UI.Button>().FirstOrDefault(b=>b.isActiveAndEnabled&&b.GetComponentInChildren<UnityEngine.UI.Text>()?.text=="Head out");
   Check(depart&&depart.interactable,"Night board exposes enabled Head out button");depart.onClick.Invoke();
   Check(game.Data.runActive&&game.Data.runNumber==1&&game.Playing&&!game.Paused&&!game.DenOpen&&game.Player.Running,"Head out starts first outing and restores movement");
   Check(game.AtHome,"Head out preserves physical Den position; departure requires walking");
   Walk(new Vector3(-14,-2.35f,56),ClosingTimeWorld.DenEntrance,new Vector3(-14,.05f,46.5f));Check(!game.AtHome,"First outing walks continuously out to avenue");
   Walk(ClosingTimeWorld.DenEntrance,new Vector3(-14,-2.35f,56),ClosingTimeWorld.DenInterior);Check(game.AtHome,"Walking through ramp enters safe den");
   game.UI.OpenDenForPlaytest();Check(game.DenOpen&&game.Paused,"Stash opens management in den");
   game.Data.pantry.AddRange(game.Items.Values.Where(i=>i.category!="trophy"&&i.category!="valuable").OrderBy(i=>i.id).Take(45).Select(i=>i.id));game.Data.pantry.Add("item_002");game.Data.bag.Add("trophy_00");game.Data.bag.Add("item_136");game.Deposit();Check(game.Data.bag.Count==0&&game.Data.trophies.Contains("trophy_00"),"Depositing banks keepsake and clears pockets");
   game.Resume();Walk(new Vector3(-12,-2.35f,58.1f),new Vector3(-11.6f,-2.35f,58.1f));Check(game.NearCollector,"Collector is reachable beside the counter");game.Search();Check(game.DenOpen&&game.Paused,"Nearby search opens collector safely");int run=game.Data.bankedRuns,trades=game.Data.collectorTrades,coins=game.Data.coins,pantry=game.Data.pantry.Count;Check(game.TradeWithCollector(run,trades),"Real collector API completes banked trade");Check(game.Data.coins==coins+8&&game.Data.pantry.Count==pantry-2,"Trade charges exact snacks and credits reward");Check(!game.TradeWithCollector(run,trades),"Repeated trade callback cannot pay twice");
   game.Resume();Walk(new Vector3(-14,-2.35f,58.6f),new Vector3(-17.6f,-2.35f,58.6f),new Vector3(-18,-2.35f,59.6f));Check(game.NearClothesRail,"Clothes rail is physically reachable");game.Search();Check(game.DenOpen&&game.Paused,"Rail interaction opens wardrobe");game.Resume();Walk(new Vector3(-17.6f,-2.35f,58.6f),new Vector3(-14,-2.35f,58.6f),ClosingTimeWorld.DenInterior);game.UI.OpenDenForPlaytest();
   string before=JsonUtility.ToJson(game.Data);displayed=DenCollection.Select(game.Data,game.Items,ClosingTimeWorld.DenDisplaySlots.Count);Check(JsonUtility.ToJson(game.Data)==before,"Selection never mutates inventory");Check(displayed.Count==32&&displayed.Distinct().Count()==32,"Display capacity is32 unique owned finds");Check(displayed[0]=="trophy_00","Trophy precedes ordinary collection");Check(game.DenDisplayedIds.SequenceEqual(displayed),"Session display order matches deterministic selection");var savedPosition=game.Player.transform.position;game.Data.x=savedPosition.x;game.Data.y=savedPosition.y;game.Data.z=savedPosition.z;saved=JsonUtility.ToJson(game.Data);Next(2);return;}
  if(stage==2){VerifyDisplays();var restored=JsonUtility.FromJson<SaveData>(saved);typeof(GameSession).GetMethod("Begin",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(game,new object[]{restored});Next(3);return;}
  if(stage==3){Check(game.Data.collectorTrades==1&&game.Data.collectorLastRun==game.Data.bankedRuns,"Trade ledger persists through reconstruction");Check(game.Data.outfit=="bandana"&&game.Data.coat==1,"Appearance persists through real session reconstruction");Check(game.DenDisplayedIds.SequenceEqual(displayed),"Saved-state reload reconstructs identical display IDs/order");Check(game.Data.pantry.SequenceEqual(JsonUtility.FromJson<SaveData>(saved).pantry),"Reload preserves pantry");VerifyDisplays();Walk(new Vector3(-14,-2.35f,56),ClosingTimeWorld.DenEntrance,new Vector3(-14,.05f,46.5f));Check(!game.AtHome,"Walking out returns to avenue");Check(cameraSamples>120,"Follow camera clears ramp/interior across "+cameraSamples+" movement samples");foreach(var pair in originals)Check(pair.Value==null?!File.Exists(pair.Key):File.Exists(pair.Key)&&pair.Value.SequenceEqual(File.ReadAllBytes(pair.Key)),"Native save unchanged: "+Path.GetFileName(pair.Key));Check(game.SuppressSaving,"Saving remained suppressed");report.passed=true;Finish();}
 }catch(Exception e){if(report==null)report=new Report();report.error=e.ToString();Debug.LogException(e);Finish();}}
 static void Finish(){var path=Path.GetFullPath("../Logs/den-experience-audit.json");Directory.CreateDirectory(Path.GetDirectoryName(path));File.WriteAllText(path,JsonUtility.ToJson(report,true));Debug.Log("DEN_EXPERIENCE_AUDIT "+(report.passed?"PASS":"FAIL"));SessionState.SetBool(Pending,false);EditorApplication.update-=Tick;EditorApplication.isPlaying=false;if(Application.isBatchMode)EditorApplication.Exit(report.passed?0:1);}
}
}
