using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
namespace Jimothy.Editor {
/// <summary>Isolated behavioral checks for persistent personalization and physical instrument/display integration.</summary>
[InitializeOnLoad] public static class DenPolishAudit {
 const string Pending="Jimothy.DenPolishAudit";static GameSession game;static int stage,frame,paidCoins;static double deadline;static string saved;static string[] expectedFavorites;static Report report;
 [Serializable] class Report {public bool passed;public string error;public List<string> assertions=new();public string method="Isolated NewGame, saving suppressed before construction. Explicit test inventory; public purchase/hide/show/pin actions; JSON save-state roundtrip into production Begin reconstruction. No native save reads/writes. Actual scene renderers, imported meshes/materials and shelf-support raycasts. Not a native performance or human-playtest result.";}
 static DenPolishAudit(){EditorApplication.playModeStateChanged+=OnMode;if(SessionState.GetBool(Pending,false))EditorApplication.update+=Tick;}
 public static void Run(){if(EditorApplication.isPlaying)throw new InvalidOperationException("Stop play mode before this isolated audit.");EditorSceneManager.OpenScene("Assets/Jimothy/Scenes/Ballard.unity");SessionState.SetBool(Pending,true);EditorApplication.isPlaying=true;}
 static void OnMode(PlayModeStateChange mode){if(mode!=PlayModeStateChange.EnteredPlayMode||!SessionState.GetBool(Pending,false))return;stage=0;deadline=EditorApplication.timeSinceStartup+150;EditorApplication.update-=Tick;EditorApplication.update+=Tick;}
 static void Check(bool okay,string description){if(!okay)throw new Exception(description);report.assertions.Add(description);}
 static void Next(int n){stage=n;frame=Time.frameCount;}
 static int Cushions()=>UnityEngine.Object.FindObjectsByType<Transform>(FindObjectsSortMode.None).Count(t=>t.name=="Patchwork cushion"&&t.gameObject.activeInHierarchy&&t.GetComponent<Renderer>()&&t.GetComponent<Renderer>().enabled);
 static void Instrument(string name,float minHeight,float maxHeight){var obj=GameObject.Find("Authored Blender "+name);Check(obj,"Custom Blender "+name+" instance present");var meshes=obj.GetComponentsInChildren<MeshFilter>();Check(meshes.Length>0&&meshes.Sum(m=>m.sharedMesh?m.sharedMesh.vertexCount:0)>1000,name+" has detailed imported geometry rather than a primitive placeholder");var renderers=obj.GetComponentsInChildren<Renderer>();Check(renderers.Length>0,name+" has renderers");var bounds=renderers[0].bounds;foreach(var renderer in renderers){bounds.Encapsulate(renderer.bounds);foreach(var material in renderer.sharedMaterials){Check(material&&material.shader&&material.shader.isSupported&&!material.shader.name.Contains("InternalError"),name+" material is supported");if(material.name.Contains("Maple")||material.name.Contains("Butterscotch")||material.name.Contains("Tolex")||material.name.Contains("Grille"))Check(material.HasProperty("_BaseMap")&&material.GetTexture("_BaseMap"),name+" authored surface texture bound: "+material.name);}}
  Check(float.IsFinite(bounds.center.x)&&float.IsFinite(bounds.center.y)&&float.IsFinite(bounds.center.z)&&float.IsFinite(bounds.size.x)&&float.IsFinite(bounds.size.y)&&float.IsFinite(bounds.size.z)&&bounds.size.x>.1f&&bounds.size.z>.01f&&bounds.size.y>minHeight&&bounds.size.y<maxHeight,name+" has finite, plausible metre-scale bounds");Check(bounds.size.x<(name=="Guitar"?.7f:1f)&&bounds.size.z<(name=="Guitar"?.3f:.6f),name+" width and depth preserve upright authored proportions");
 }
 static void PhysicalChecks(){Physics.SyncTransforms();Check(ClosingTimeWorld.DenDisplaySlots.Count==32,"32 display anchors retained after instrument replacement");for(int i=0;i<ClosingTimeWorld.DenDisplaySlots.Count;i++){var p=ClosingTimeWorld.DenDisplaySlots[i];bool hit=Physics.Raycast(p+Vector3.up*.05f,Vector3.down,out var support,.12f,1,QueryTriggerInteraction.Ignore);Check(hit&&support.normal.y>.8f&&Mathf.Abs(support.point.y-p.y)<.015f,"Display anchor "+i+" sits on a physical support");}
  var models=UnityEngine.Object.FindObjectsByType<DenDisplayedFind>(FindObjectsSortMode.None);Check(models.Length==32&&models.Select(m=>m.itemId).Distinct().Count()==32,"32 unique physical finds rebuilt");foreach(var model in models){var b=model.GetComponent<Renderer>().bounds;Check(Physics.Raycast(new Vector3(b.center.x,b.min.y+.04f,b.center.z),Vector3.down,.13f,1,QueryTriggerInteraction.Ignore),"Displayed find has support below: "+model.itemId);}Instrument("Guitar",1.04f,1.16f);Instrument("Amp",.50f,.62f);
 }
 static void Tick(){if(!SessionState.GetBool(Pending,false)||!EditorApplication.isPlaying)return;try{
  if(EditorApplication.timeSinceStartup>deadline)throw new Exception("DenPolishAudit timeout");
  if(stage==0){game=UnityEngine.Object.FindFirstObjectByType<GameSession>();if(!game)return;report=new Report();game.SuppressSaving=true;game.NewGame();Next(1);return;}
  if(Time.frameCount-frame<20)return;
  if(stage==1){game.Player.Teleport(ClosingTimeWorld.DenInterior);game.Player.Running=false;Check(game.AtHome,"Personalization fixture is inside physical den");for(int i=208;i<=239;i++)game.Data.bag.Add("item_"+i);for(int i=0;i<10;i++)game.Data.bag.Add("trophy_"+i.ToString("00"));game.Deposit();Check(game.Data.bag.Count==0,"Production deposit banks fixture inventory");game.Data.coins=500;game.BuyDecor("cushion",0);paidCoins=game.Data.coins;Check(paidCoins<500&&paidCoins>=0&&game.Data.decor.Count(id=>id=="cushion")==1,"First cushion purchase charges its catalog price once");
   game.ToggleFavorite("item_000");game.ToggleFavorite("not-a-catalog-id");Check(game.Data.favoriteFinds.Count==0,"Unowned and unknown items cannot be pinned");for(int i=232;i<=239;i++)game.ToggleFavorite("item_"+i);Check(game.Data.favoriteFinds.Count==8,"Eight owned finds can be pinned");game.ToggleFavorite("item_231");Check(game.Data.favoriteFinds.Count==8&&!game.Data.favoriteFinds.Contains("item_231"),"Ninth favorite is refused without changing existing pins");game.ToggleFavorite("item_232");game.ToggleFavorite("item_231");Check(game.Data.favoriteFinds.Count==8&&game.Data.favoriteFinds.Contains("item_231")&&!game.Data.favoriteFinds.Contains("item_232"),"Unpinning releases a slot for another owned find");expectedFavorites=game.Data.favoriteFinds.ToArray();Next(2);return;}
  if(stage==2){Check(Cushions()==1,"Purchased cushion is physically visible");Check(expectedFavorites.All(id=>game.DenDisplayedIds.Take(8).Contains(id)),"Pinned finds appear in the first eight physical display slots");game.ToggleDecoration("not-owned");Check(game.Data.hiddenDecor.Count==0,"Unowned furnishing visibility cannot be changed");game.ToggleDecoration("cushion");Check(game.Data.decor.Contains("cushion")&&game.Data.hiddenDecor.Contains("cushion")&&game.Data.coins==paidCoins,"Hiding keeps ownership and coins unchanged");Next(3);return;}
  if(stage==3){Check(Cushions()==0,"Hidden purchased cushion is absent from scene");var pos=game.Player.transform.position;game.Data.x=pos.x;game.Data.y=pos.y;game.Data.z=pos.z;saved=JsonUtility.ToJson(game.Data);var restored=JsonUtility.FromJson<SaveData>(saved);Check(restored.Valid()&&restored.hiddenDecor.SequenceEqual(game.Data.hiddenDecor)&&restored.favoriteFinds.SequenceEqual(expectedFavorites),"Serialized save state roundtrips hidden decor and favorites");typeof(GameSession).GetMethod("Begin",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(game,new object[]{restored});Next(4);return;}
  if(stage==4){game.Player.Running=false;Check(game.Data.hiddenDecor.Contains("cushion")&&game.Data.favoriteFinds.SequenceEqual(expectedFavorites),"Session reconstruction restores personalization");Check(game.Data.coins==paidCoins&&game.Data.pantry.Count==32&&game.Data.trophies.Count==10,"Reconstruction preserves coins and inventory");Check(Cushions()==0,"Hidden furnishing stays hidden after session reconstruction");Check(expectedFavorites.All(id=>game.DenDisplayedIds.Take(8).Contains(id)),"Favorite display priority survives reload");game.ToggleDecoration("cushion");game.BuyDecor("cushion",999);Check(game.Data.coins==paidCoins&&game.Data.decor.Count(id=>id=="cushion")==1&&!game.Data.hiddenDecor.Contains("cushion"),"Showing and repeat purchase never charge again or duplicate ownership");Next(5);return;}
  if(stage==5){Check(Cushions()==1,"Showing a purchased furnishing restores exactly one visible model");PhysicalChecks();
   var denPosition=game.Player.transform.position;game.Player.Teleport(new Vector3(-3,12,44));game.Player.SimulateMovement(Vector3.zero,false,1f/60);Physics.SyncTransforms();game.FastTravel();Check(game.Player.transform.position.y>11,"Fast travel cannot cancel an airborne fall");game.Player.Teleport(denPosition);
   int beforeCoins=game.Data.coins;game.ResolveLanding(1000,"Clean flip",0,true);Check(game.Data.trickScore==1000&&game.Data.bestLandingScore==1000&&game.Data.coins==beforeCoins+5,"Clean style milestone grants five shinies and persists a best landing");
   typeof(GameSession).GetField("invulnerable",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(game,10f);float beforeHealth=game.Data.health;game.ResolveLanding(2000,"Unsafe flip",30,false);Check(Mathf.Abs(game.Data.health-(beforeHealth-30))<.01f&&game.Data.trickScore==1000&&game.Data.coins==beforeCoins+5,"Fall damage bypasses enemy immunity and awards no unsafe points or currency");
   var styleSave=JsonUtility.FromJson<SaveData>(JsonUtility.ToJson(game.Data));Check(styleSave.Valid()&&styleSave.trickScore==1000&&styleSave.bestLandingScore==1000&&styleSave.trickRewardMilestones==1&&styleSave.bankedDiscoveries.Count==42,"Save roundtrip retains style records, paid reward milestones and permanent collection progress");
   game.Data.pantry.Add("item_000");game.ToggleFavorite("item_231");game.ToggleFavorite("item_000");Check(game.Data.favoriteFinds.Contains("item_000"),"Owned food can be pinned when a display slot is free");game.Data.pantry.Remove("item_000");game.ToggleDecoration("cushion");Check(!game.Data.favoriteFinds.Contains("item_000"),"Consumed last-copy finds release a stale favorite slot");
   Check(game.SuppressSaving,"Saving remained suppressed throughout audit");report.passed=true;Finish();}
 }catch(Exception e){report??=new Report();report.error=e.ToString();Debug.LogException(e);Finish();}}
 static void Finish(){string path=Path.GetFullPath("../Logs/den-polish-audit.json");Directory.CreateDirectory(Path.GetDirectoryName(path));File.WriteAllText(path,JsonUtility.ToJson(report,true));Debug.Log("DEN_POLISH_AUDIT "+(report.passed?"PASS":"FAIL"));SessionState.SetBool(Pending,false);EditorApplication.update-=Tick;EditorApplication.isPlaying=false;if(Application.isBatchMode)EditorApplication.Exit(report.passed?0:1);}
}}
