using System;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.Rendering;
namespace Jimothy.Editor {
[InitializeOnLoad] public static class DiscoveryRevealAudit {
 const string Pending="Jimothy.DiscoveryRevealAudit";static GameSession game;static Camera camera;static RenderTexture target;static int stage,layout,id=9000,frame,bag;static double ready,deadline;static float health;static double world;static Vector3 position;static Report report;static string folder;static bool oldMobile;static ItemDefinition trophy,rare,common;
 [Serializable] class Report {public bool passed,savingSuppressed;public string error,method="Full production world, NewGame and StartNight with saving suppressed before construction. Production Collect with isolated unused node IDs and catalog items. Runtime update waits, not manual paused physics. Desktop1600x900/mobile1688x780 editor renders with camera canvases; not native-device or performance evidence. Settings viewed without changing preferences.";public List<string> assertions=new(),images=new();}
 static DiscoveryRevealAudit(){EditorApplication.playModeStateChanged+=Changed;if(SessionState.GetBool(Pending,false))EditorApplication.update+=Tick;}
 public static void Run(){if(EditorApplication.isPlaying)throw new InvalidOperationException("Stop existing play mode first.");EditorSceneManager.OpenScene("Assets/Jimothy/Scenes/Ballard.unity");SessionState.SetBool(Pending,true);EditorApplication.isPlaying=true;}
 static void Changed(PlayModeStateChange mode){if(mode!=PlayModeStateChange.EnteredPlayMode||!SessionState.GetBool(Pending,false))return;stage=0;layout=0;id=9000;report=new Report();oldMobile=GameUI.ForceMobileLayout;deadline=EditorApplication.timeSinceStartup+180;folder=Path.GetFullPath("../PlaytestCaptures/discovery-reveal");Directory.CreateDirectory(folder);EditorApplication.update-=Tick;EditorApplication.update+=Tick;}
 static void Check(bool okay,string text){if(!okay)throw new Exception(text);report.assertions.Add(text);}
 static DiscoveryReveal Reveal=>game.GetComponent<DiscoveryReveal>();
 static void Wait(int next,float seconds=.6f){stage=next;ready=EditorApplication.timeSinceStartup+seconds;frame=Time.frameCount;PrepareCanvases();}
 static void PrepareCanvases(){if(!camera)return;foreach(var c in game.GetComponentsInChildren<Canvas>()){c.renderMode=RenderMode.ScreenSpaceCamera;c.worldCamera=camera;c.planeDistance=1;}Canvas.ForceUpdateCanvases();}
 static void SetLayout(){if(target){camera.targetTexture=null;target.Release();UnityEngine.Object.Destroy(target);}int w=layout==0?1600:1688,h=layout==0?900:780;target=new RenderTexture(w,h,24,RenderTextureFormat.ARGB32){antiAliasing=2,name="Discovery audit capture RGBA"};target.Create();camera.targetTexture=target;camera.aspect=(float)w/h;GameUI.ForceMobileLayout=layout==1;game.UI.ShowHUD();PrepareCanvases();}
 static void CollectModal(ItemDefinition item){game.Player.touchMove=Vector2.one;game.Player.touchLook=Vector2.one;game.Player.jumpRequested=true;int prior=game.Data.bag.Count;int node=id++;Check(game.Available(node),"Fixture node available before collect "+node);Check(game.Collect(node,item),"Collect accepts "+item.name);Check(game.DiscoveryOpen&&game.Paused&&!game.Player.Running&&Reveal.IsCelebrating,"Rare/trophy collection opens safe modal");Check(game.Data.bag.Count==prior+1,"Collection increments bag exactly once");Check(game.Player.touchMove==Vector2.zero&&game.Player.touchLook==Vector2.zero&&!game.Player.jumpRequested,"Modal opening clears held touch and jump");Check(!game.Collect(node,item)&&!game.Collect(id+100,item),"Modal blocks duplicate and additional collection");position=game.Player.transform.position;health=game.Data.health;world=game.Data.worldSeconds;bag=game.Data.bag.Count;Reveal.Dismiss();Check(game.DiscoveryOpen,"Opening dismiss is debounced");game.Player.touchMove=Vector2.one;game.Player.touchLook=Vector2.one;game.Player.jumpRequested=true;}
 static void Frozen(){Check(game.Paused&&!game.Player.Running&&game.DiscoveryOpen,"Modal remains paused after runtime wait");Check(Vector3.Distance(position,game.Player.transform.position)<.001f,"Modal freezes actual motor position");Check(Mathf.Abs(game.Data.health-health)<.001f&&Math.Abs(game.Data.worldSeconds-world)<.001f,"Modal freezes health and session clock");Check(game.Data.bag.Count==bag,"Modal wait does not duplicate inventory");}
 static Button ModalButton(){PrepareCanvases();var canvas=game.GetComponentsInChildren<Canvas>().Single(c=>c.name=="Treasure celebration");var button=canvas.GetComponentInChildren<Button>();Check(canvas.GetComponent<GraphicRaycaster>()&&EventSystem.current,"Modal has raycaster and active event system");var point=RectTransformUtility.WorldToScreenPoint(camera,button.GetComponent<RectTransform>().TransformPoint(button.GetComponent<RectTransform>().rect.center));var data=new PointerEventData(EventSystem.current){position=point};var hits=new List<RaycastResult>();EventSystem.current.RaycastAll(data,hits);Check(hits.Count>0&&hits[0].gameObject.GetComponentInParent<Button>()==button,"Continue button wins actual UI raycast");data.position=new Vector2(target.width*.015f,target.height*.5f);hits.Clear();EventSystem.current.RaycastAll(data,hits);Check(hits.Count>0&&hits[0].gameObject.name=="Input shield","Modal background shields gameplay UI from pointer hits");return button;}
 static void Dismiss(){var button=ModalButton();ExecuteEvents.Execute(button.gameObject,new PointerEventData(EventSystem.current){button=PointerEventData.InputButton.Left},ExecuteEvents.pointerClickHandler);Check(!game.DiscoveryOpen&&!game.Paused&&game.Player.Running&&!Reveal.IsOpen,"Dismiss resumes outing and closes modal");Check(game.Player.touchMove==Vector2.zero&&game.Player.touchLook==Vector2.zero&&!game.Player.jumpRequested,"Dismiss clears touch held during modal");Check(!game.Collect(id-1,trophy),"Previously collected node remains unavailable after resume");}
 static void Capture(string name){PrepareCanvases();RenderPipeline.SubmitRenderRequest(camera,new RenderPipeline.StandardRequest{destination=target});var resolve=RenderTexture.GetTemporary(target.width,target.height,0,RenderTextureFormat.ARGB32,RenderTextureReadWrite.sRGB);var old=RenderTexture.active;Graphics.Blit(target,resolve);RenderTexture.active=resolve;var image=new Texture2D(target.width,target.height,TextureFormat.RGBA32,false);image.ReadPixels(new Rect(0,0,target.width,target.height),0,0);image.Apply();string file=(layout==0?"desktop-":"mobile-")+name+".png";File.WriteAllBytes(Path.Combine(folder,file),image.EncodeToPNG());report.images.Add(file);RenderTexture.active=old;UnityEngine.Object.Destroy(image);RenderTexture.ReleaseTemporary(resolve);
  if(Reveal&&Reveal.IsOpen){var rt=(RenderTexture)typeof(DiscoveryReveal).GetField("target",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(Reveal);var copy=RenderTexture.GetTemporary(rt.width,rt.height,0,RenderTextureFormat.ARGB32);Graphics.Blit(rt,copy);RenderTexture.active=copy;var portrait=new Texture2D(rt.width,rt.height,TextureFormat.RGBA32,false);portrait.ReadPixels(new Rect(0,0,rt.width,rt.height),0,0);portrait.Apply();var pixels=portrait.GetPixels32();Check(pixels[0].a<8&&pixels[rt.width-1].a<8,"Portrait render target preserves transparent background");Check(pixels.Count(p=>p.a>200)>pixels.Length/100,"Portrait contains visible rendered treasure");File.WriteAllBytes(Path.Combine(folder,(layout==0?"desktop-":"mobile-")+name+"-portrait.png"),portrait.EncodeToPNG());RenderTexture.active=old;UnityEngine.Object.Destroy(portrait);RenderTexture.ReleaseTemporary(copy);}
 }
 static void Tick(){if(!SessionState.GetBool(Pending,false)||!EditorApplication.isPlaying)return;try{
  if(EditorApplication.timeSinceStartup>deadline)throw new Exception("Discovery audit timeout");
  if(stage==0){game=UnityEngine.Object.FindFirstObjectByType<GameSession>();if(!game)return;game.SuppressSaving=true;game.NewGame();game.StartNight();report.savingSuppressed=game.SuppressSaving;camera=Camera.main;trophy=game.Items.Values.First(i=>i.category=="trophy");rare=game.Items.Values.First(i=>i.category!="trophy"&&DiscoveryReveal.DeservesCelebration(i));common=game.Items.Values.First(i=>!DiscoveryReveal.DeservesCelebration(i));game.Player.Teleport(ClosingTimeWorld.StreetStart);SetLayout();Wait(1,1);return;}
  if(EditorApplication.timeSinceStartup<ready||Time.frameCount-frame<4)return;
  if(stage==1){CollectModal(trophy);Wait(2);return;}
  if(stage==2){Frozen();Capture("trophy");Dismiss();CollectModal(rare);Wait(3);return;}
  if(stage==3){Frozen();Capture("rare");Dismiss();int before=game.Data.bag.Count;int node=id++;Check(game.Collect(node,common),"Common find collects");Check(!game.DiscoveryOpen&&!game.Paused&&game.Player.Running&&Reveal.IsOpen&&!Reveal.IsCelebrating,"Common card is nonmodal");Check(!game.Collect(node,common)&&game.Data.bag.Count==before+1,"Common duplicate is blocked while session remains running");Wait(4);return;}
  if(stage==4){Capture("common");game.TogglePause();typeof(GameUI).GetMethod("Settings",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(game.UI,new object[]{true});Wait(5);return;}
  if(stage==5){Capture("settings");Check(game.Paused&&!game.Player.Running,"Viewing settings preserves pause");game.Resume();if(layout==0){layout=1;game.Data.bag.Clear();SetLayout();Wait(1);return;}CollectModal(trophy);Wait(6);return;}
  if(stage==6){Frozen();game.TogglePause();Check(!game.DiscoveryOpen&&!Reveal.IsOpen&&game.Paused&&!game.Player.Running,"Manual pause transfers modal to pause without resuming");Wait(7);return;}
  if(stage==7){Check(game.Paused&&!game.Player.Running,"Transferred pause remains paused on later frames");game.Resume();CollectModal(rare);Wait(8);return;}
  if(stage==8){game.Menu();Check(!game.DiscoveryOpen&&!Reveal.IsOpen&&!game.Playing&&!game.Player.Running,"Menu cleans modal and stops gameplay");Wait(9);return;}
  if(stage==9){Check(!game.GetComponentsInChildren<Canvas>().Any(c=>c.name=="Treasure celebration"),"Modal overlay destroyed after menu frames");Check(!UnityEngine.Object.FindObjectsByType<Camera>(FindObjectsSortMode.None).Any(c=>c.name=="Reward portrait camera"),"Portrait camera cleaned after menu frames");Finish(true);}
 }catch(Exception e){report.error=e.ToString();Debug.LogException(e);Finish(false);}}
 static void Finish(bool passed){report.passed=passed;SessionState.SetBool(Pending,false);EditorApplication.update-=Tick;GameUI.ForceMobileLayout=oldMobile;if(camera)camera.targetTexture=null;if(target){target.Release();UnityEngine.Object.Destroy(target);target=null;}Directory.CreateDirectory(folder);File.WriteAllText(Path.Combine(folder,"audit.json"),JsonUtility.ToJson(report,true));Debug.Log("DISCOVERY_REVEAL_AUDIT "+passed);EditorApplication.isPlaying=false;if(Application.isBatchMode)EditorApplication.Exit(passed?0:2);}
}
}
