const {chromium}=require('playwright');
const fs=require('fs'),path=require('path');
(async()=>{const out=path.resolve('PlaytestCaptures/web-v047');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:false,});const context=await browser.newContext({viewport:{width:1366,height:1024},hasTouch:true,isMobile:true,deviceScaleFactor:1});const page=await context.newPage(),cdp=await context.newCDPSession(page);const checks=[],errors=[],messages=[],states={};
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{messages.push({type:m.type(),text:m.text(),stage:checks.at(-1)?.name});if(m.type()==='error')errors.push(m.text());});const state=async()=>JSON.parse(await page.evaluate(()=>window.render_game_to_text()));const wait=ms=>page.waitForTimeout(ms);const check=(name,ok)=>{checks.push({name,passed:!!ok});console.log(name+': '+!!ok);if(!ok)throw Error(name);};
const control=async name=>{const expected={'Head out':[.275,.8825],'Return to this outing':[.275,.8825],'Unload pockets':[.26,.46],'Night board & collections':[.72,.83],'Save & main menu':[.5,.79]};const s=await state();const r=s.controls.find(x=>x.name===name||x.name==='Title action · '+name)||s.controls.find(x=>x.name==='Panel'&&expected[name]&&Math.abs(x.x-expected[name][0])<.03&&Math.abs(x.y-expected[name][1])<.03);if(!r)throw Error('Missing '+name+' among '+(await state()).controls.map(x=>x.name));const v=page.viewportSize();return{x:r.x*v.width,y:r.y*v.height,w:r.w*v.width,h:r.h*v.height};};const tap=async name=>{const p=await control(name);await page.touchscreen.tap(p.x,p.y);await wait(700);};const shot=async name=>{states[name]=await state();await page.screenshot({path:path.join(out,name+'.png')});};
const loaded=async()=>{await page.locator('#start').click();await page.waitForFunction(()=>typeof window.render_game_to_text==='function'&&JSON.parse(window.render_game_to_text()).controls?.length>0,{},{timeout:180000});await wait(500);};
// Trusted touch gestures only. Read-only state supplies positions for stop conditions.
async function walk(x,z){let s=await state(),p=await control('Floating movement surface');const dx=x-s.position.x,dz=z-s.position.z,dist=Math.hypot(dx,dz);if(dist<.45)return;const h=s.heading*Math.PI/180,rx=(dx*Math.cos(h)-dz*Math.sin(h))/dist,ry=(dx*Math.sin(h)+dz*Math.cos(h))/dist;
 const a={id:8,x:p.x,y:p.y,radiusX:5,radiusY:5,force:1},b={...a,x:p.x+rx*65,y:p.y-ry*65};await Promise.all([cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]}),cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[b]})]);try{await page.waitForFunction(({x,z,dx,dz,sx,sz})=>{const p=JSON.parse(window.render_game_to_text()).position;return Math.hypot(p.x-x,p.z-z)<.42||(p.x-sx)*dx+(p.z-sz)*dz>=dx*dx+dz*dz;},{x,z,dx,dz,sx:s.position.x,sz:s.position.z},{timeout:25000,polling:100});}finally{await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[b]});}await wait(250);}
try{await page.goto('http://127.0.0.1:8765/?v=0.4.7');await loaded();check('Latest web version',(await state()).version==='0.4.7');await tap('New adventure');await shot('ipad-night-board');check('New game opens safe night board',(await state()).mode==='paused'&&!(await state()).runActive);await tap('Head out');check('Head out starts night one',(await state()).runActive&&(await state()).runNumber===1);await shot('ipad-den-departure');
for(const [x,z] of [[-14,55],[-14,49],[-10,44],[-3,44]])await walk(x,z);check('Touch movement exits physical Den to street',(await state()).position.z<45);await tap('Nearby interaction');await wait(2800);check('Search carries a find without banking',(await state()).bag===1&&(await state()).coins===0&&(await state()).consumedNodes===1);await shot('street-loose-haul');
const saved=await state();await tap('Travel to Den');check('Loose haul prevents fast travel',(await state()).position.z<46);await tap('Pause');await tap('Save & main menu');await page.reload();await loaded();await tap('Continue adventure');await wait(900);const resumed=await state();check('Browser reload retains active outing and consumed loot',resumed.runActive&&resumed.runNumber===saved.runNumber&&resumed.forageSeed===saved.forageSeed&&resumed.bag===1&&resumed.consumedNodes===1);await shot('resumed-haul');
for(const [x,z] of [[-10,44],[-14,49],[-14,55],[-14,59]])await walk(x,z);await tap('Nearby interaction');await tap('Unload pockets');check('Den banks find once',!(await state()).runActive&&(await state()).banked===1&&(await state()).coins===1);await tap('Unload pockets');check('Repeated banking does not mint coins',(await state()).coins===1);await tap('Night board & collections');await shot('ipad-banked-board');await tap('Head out');check('Next outing rotates goal and refreshes loot',(await state()).runNumber===2&&(await state()).goal===1&&(await state()).consumedNodes===0);await page.setViewportSize({width:932,height:430});await wait(600);await shot('iphone-hud');const j=await control('Jump and trick');check('Phone jump remains finger sized',j.w>=70&&j.h>=70);await tap('Nearby interaction');await tap('Night board & collections');await shot('iphone-night-board');await tap('Return to this outing');await page.setViewportSize({width:430,height:932});await wait(500);check('Portrait safely pauses outing',(await state()).mode==='paused');await shot('portrait');check('No runtime browser errors',errors.length===0);
}catch(e){errors.push(e.stack);process.exitCode=1;await shot('failure').catch(()=>{});}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors,messages,states},null,2));console.log(JSON.stringify({checks,errors}));await browser.close();}})();
