const {chromium}=require('/path/to/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path');
(async()=>{const out=path.resolve('PlaytestCaptures/web-v046');fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:false,executablePath:"/path/to/user/Library/Caches/ms-playwright/chromium-1208/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing"});const context=await browser.newContext({viewport:{width:1366,height:1024},hasTouch:true,isMobile:true,deviceScaleFactor:1});const page=await context.newPage();const cdp=await context.newCDPSession(page);let points=[];const checks=[],errors=[],states={};
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const state=async()=>JSON.parse(await page.evaluate(()=>window.render_game_to_text()));const wait=ms=>page.waitForTimeout(ms);const check=(name,ok)=>{checks.push({name,passed:!!ok});if(!ok)throw Error(name);};
const control=async name=>{const s=await state(),r=s.controls.find(x=>x.name===name);if(!r)throw Error('Missing control '+name);const v=page.viewportSize();return{x:r.x*v.width,y:r.y*v.height,w:r.w*v.width,h:r.h*v.height};};
const flick=async(p,dx,dy)=>{const a={id:1,x:p.x,y:p.y,radiusX:5,radiusY:5,force:1},b={...a,x:p.x+dx,y:p.y+dy};await Promise.all([cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[a]}),cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[b]}),cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[b]})]);};
const dispatch=async type=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points});const down=async(id,x,y)=>{points.push({id,x,y,radiusX:5,radiusY:5,force:1});await dispatch('touchStart');};const move=async(id,x,y)=>{Object.assign(points.find(p=>p.id===id),{x,y});await dispatch('touchMove');};const up=async id=>{await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:points.filter(p=>p.id===id)});points=points.filter(p=>p.id!==id);};const tap=async name=>{const p=await control(name);await page.touchscreen.tap(p.x,p.y);await wait(300);};const shot=async name=>{await page.screenshot({path:path.join(out,name+'.png')});states[name]=await state();};
try{await page.addInitScript(()=>{window.touchEvents=[];for(const type of ['touchstart','touchmove','touchend','touchcancel'])document.addEventListener(type,e=>{window.touchEvents.push({time:performance.now(),type,cancelable:e.cancelable,target:e.target.id,active:[...e.touches].map(t=>t.identifier),changed:[...e.changedTouches].map(t=>t.identifier)});},{capture:true,passive:true});});await page.goto('http://127.0.0.1:8765/?v=0.4.6');await page.locator('#start').click();await page.waitForFunction(()=>typeof window.render_game_to_text==='function',{},{timeout:180000});await wait(3000);check('Version 0.4.6 loaded',(await state()).version==='0.4.6');await down(3,270,635);await wait(300);await up(3);await wait(1800);await shot('ipad-controls');check('New adventure playable',(await state()).mode==='playing');const j=await control('Jump and trick');check('Primary action is circular',Math.abs(j.w-j.h)<2);await tap('Nearby interaction');await wait(2600);check('Context search collects snack',(await state()).bag===1);check('Search disappears out of context',!(await state()).controls.some(x=>x.name==='Nearby interaction'));
for(const [name,dx,dy] of [['Frontflip',0,-80],['Backflip',0,80],['Left barrel roll',-80,0],['Right barrel roll',80,0]]){const before=(await state()).trickScore;const p=await control('Jump and trick');await flick(p,dx,dy);await wait(1100);await shot('trick-'+name.replaceAll(' ','-'));const s=await state();check(name+' gesture lands and scores once',s.trickScore===before+150&&s.lastTrick===name&&s.health===100);}
const before=(await state()).trickScore;{const p=await control('Jump and trick');await down(1,p.x,p.y);await move(1,p.x+7,p.y-7);await up(1);await wait(1100);}check('Tap/jitter jumps without accidental trick',(await state()).trickScore===before);
{const p=await control('Camera gesture surface'),s=await state();await down(2,p.x-60,p.y-90);await move(2,p.x+65,p.y-90);await up(2);await wait(400);const now=await state();check('Camera drag rotates without trick',Math.abs(now.heading-s.heading)>5&&now.trickScore===s.trickScore);}
{const p=await control('Floating movement surface'),j=await control('Jump and trick'),s=await state();await down(2,p.x,p.y);await move(2,p.x,p.y-65);await wait(200);await down(1,j.x,j.y);await move(1,j.x,j.y-80);await up(1);await wait(3000);check('Lifting trick finger preserves held movement',(await state()).touchMove.y>.5);await up(2);await wait(500);const now=await state();check('Move and trick together work',Math.hypot(now.position.x-s.position.x,now.position.z-s.position.z)>1&&now.trickScore>s.trickScore);check('Stick releases to neutral',now.touchMove.x===0&&now.touchMove.y===0);}
await page.setViewportSize({width:932,height:430});await wait(600);await shot('iphone-controls');const small=await control('Jump and trick');check('Phone primary action remains finger sized',small.w>=70&&small.h>=70);const p=await control('Jump and trick'),score=(await state()).trickScore;await down(1,p.x,p.y);await move(1,p.x-55,p.y);await up(1);await wait(1100);check('Phone directional swipe scores',(await state()).trickScore>score);await shot('iphone-landing');await tap('Pause');await page.touchscreen.tap(638,267);await wait(400);await shot('touch-help');await page.touchscreen.tap(300,346);await wait(250);await shot("tap-setting");await page.touchscreen.tap(720,346);await wait(250);await page.touchscreen.tap(466,193);await wait(400);const jp=await control('Jump and trick'),old=(await state()).trickScore;const tapPoint={id:4,x:jp.x,y:jp.y,radiusX:5,radiusY:5,force:1};await Promise.all([cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[tapPoint]}),cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[tapPoint]})]);await page.waitForFunction(()=>!JSON.parse(window.render_game_to_text()).grounded,{},{timeout:3000});tapPoint.id=5;await Promise.all([cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[tapPoint]}),cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[tapPoint]})]);await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).grounded,{},{timeout:10000});check('Optional tap-in-air scheme works',(await state()).trickScore===old+150);
await page.setViewportSize({width:430,height:932});await wait(500);await shot('portrait-paused');check('Portrait pauses and releases controls',(await state()).mode==='paused'&&(await state()).touchMove.y===0);check('No browser runtime errors',errors.length===0);
}catch(e){errors.push(e.stack||e.message);states.failure=await state();await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({checks,errors,states,touchEvents:await page.evaluate(()=>window.touchEvents).catch(()=>[])},null,2));console.log(JSON.stringify({checks,errors}));await browser.close();}})();
